MODEL:
  NAME: resnet50
  RES4_STRIDE: 1
  FEATURE_DIM: 4096
  CA_DIM: 2048
  POOLING:
    NAME: maxavg
    P: 3
  USE_OLD_FEATURE: True
  PATCH_SHUFFLE: True
  DECOUPLE: True
  NUM_DECOUPLE_BLOCKS: 2
  SIM: False
DATA:
  HEIGHT: 384
  WIDTH: 192
LOSS:
  CLA_LOSS: crossentropylabelsmooth
  CLOTHES_CLA_LOSS: crossentropy
  CAL: cal
  CLA_LOSS_WEIGHT: 1.0
  ID_LOSS_WEIGHT: 0.0
  CLO_LOSS_WEIGHT: 0.0
  SIM_LOSS_WEIGHT: 0.0
TRAIN:
  MAX_EPOCH: 60
  OPTIMIZER:
    NAME: adam
    LR: 0.00035
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    NAME: warmup
    WARMUP_EPOCH: 0
    STEPSIZE: [20, 40]
TEST:
  CAM_LAYER: layer4
    
# TAG: res50-cels-cal