MODEL:
  NAME: vit
  FEATURE_DIM: 768
  CA_DIM: 768
  POOLING:
    NAME: maxavg
    P: 3
  USE_OLD_FEATURE: False
  PATCH_SHUFFLE: False
  DECOUPLE: False
  USE_PROMPT: False
DATA:
  HEIGHT: 384
  WIDTH: 192
LOSS:
  CLA_LOSS: crossentropylabelsmooth
  CAL: cal
  CLA_LOSS_WEIGHT: 1.0
  ID_LOSS_WEIGHT: 0.0
  CLO_LOSS_WEIGHT: 0.0
  ORTHO_LOSS_WEIGHT: 0.0
TRAIN:
  MAX_EPOCH: 60
  OPTIMIZER:
    NAME: sgd
    LR: 0.0035
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    NAME: warmup
    WARMUP_EPOCH: 0
    STEPSIZE: [40]
